//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace IndignadoFramework.Entities
{
    
    
    public class ConvocatoriaMetaData
    {
    	[Display(Name ="Id")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int Id { get; set; }
    	
    	[Display(Name ="Inicio")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual System.DateTime Inicio { get; set; }
    	
    	[Display(Name ="UbicacionLatitud")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual double UbicacionLatitud { get; set; }
    	
    	[Display(Name ="UbicacionLongitud")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual double UbicacionLongitud { get; set; }
    	
    	[Display(Name ="Descripcion")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual string Descripcion { get; set; }
    	
    	[Display(Name ="Quorum")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int Quorum { get; set; }
    	
    	[Display(Name ="Titulo")]
    	[StringLength(45, ErrorMessage="Debe ingresar menos de 45 caracteres")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual string Titulo { get; set; }
    	
    	[Display(Name ="MovimientoId")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int MovimientoId { get; set; }
    	
    	[Display(Name ="CategoriaTematicaId")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int CategoriaTematicaId { get; set; }
    	
    	[Display(Name ="CantUsuariosConfirmados")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int CantUsuariosConfirmados { get; set; }
    	
    	[Display(Name ="Suspendida")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual bool Suspendida { get; set; }
    	
    }
}
