//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace IndignadoFramework.Entities
{
    /// <summary>
    /// DECLARED ONLY TO MAKE PROJECTIONS OVER LINQ TO ENTITIES 
    /// </summary>
    public class EspecificacionUsuarioProjection : EspecificacionUsuario
    {
    }
}
