//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace IndignadoFramework.Entities
{
    
    
    public class FuenteWEBMetaData
    {
    	[Display(Name ="Id")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int Id { get; set; }
    	
    	[Display(Name ="Url")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual string Url { get; set; }
    	
    	[Display(Name ="Tipo")]
    	[StringLength(45, ErrorMessage="Debe ingresar menos de 45 caracteres")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual string Tipo { get; set; }
    	
    	[Display(Name ="MovimientoId")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int MovimientoId { get; set; }
    	
    	[Display(Name ="UrlDll")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual string UrlDll { get; set; }
    	
    }
}
