//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace IndignadoFramework.Entities
{
    
    
    public class MegustaMetaData
    {
    	[Display(Name ="Id")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int Id { get; set; }
    	
    	[Display(Name ="Fecha")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual System.DateTime Fecha { get; set; }
    	
    	[Display(Name ="ContenidoId")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int ContenidoId { get; set; }
    	
    	[Display(Name ="EspecificacionUsuarioId")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int EspecificacionUsuarioId { get; set; }
    	
    }
}
