//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace IndignadoFramework.Entities
{
    [Serializable]
    [DataContractAttribute(IsReference = true)]
    [KnownType(typeof(MegustaProjection))]
    [MetadataType(typeof(MegustaMetaData))]
    public partial class Megusta 
    {
        #region Primitive Properties
    
        [DataMemberAttribute()]
        public virtual int Id
        {
            get;
            set;
        }
    
        [DataMemberAttribute()]
        public virtual System.DateTime Fecha
        {
            get;
            set;
        }
    
        [DataMemberAttribute()]
        public virtual int ContenidoId
        {
            get { return _contenidoId; }
            set
            {
                if (_contenidoId != value)
                {
                    if (Contenido != null && Contenido.Id != value)
                    {
                        Contenido = null;
                    }
                    _contenidoId = value;
                }
            }
        }
        private int _contenidoId;
    
        [DataMemberAttribute()]
        public virtual int EspecificacionUsuarioId
        {
            get { return _especificacionUsuarioId; }
            set
            {
                if (_especificacionUsuarioId != value)
                {
                    if (EspecificacionUsuario != null && EspecificacionUsuario.Id != value)
                    {
                        EspecificacionUsuario = null;
                    }
                    _especificacionUsuarioId = value;
                }
            }
        }
        private int _especificacionUsuarioId;

        #endregion
        #region Navigation Properties
    
        [DataMemberAttribute()]
        public virtual Contenido Contenido
        {
            get { return _contenido; }
            set
            {
                if (!ReferenceEquals(_contenido, value))
                {
                    var previousValue = _contenido;
                    _contenido = value;
                    FixupContenido(previousValue);
                }
            }
        }
        private Contenido _contenido;
    
        [DataMemberAttribute()]
        public virtual EspecificacionUsuario EspecificacionUsuario
        {
            get { return _especificacionUsuario; }
            set
            {
                if (!ReferenceEquals(_especificacionUsuario, value))
                {
                    var previousValue = _especificacionUsuario;
                    _especificacionUsuario = value;
                    FixupEspecificacionUsuario(previousValue);
                }
            }
        }
        private EspecificacionUsuario _especificacionUsuario;

        #endregion
        #region Association Fixup
    
        private void FixupContenido(Contenido previousValue)
        {
            if (previousValue != null && previousValue.Megusta.Contains(this))
            {
                previousValue.Megusta.Remove(this);
            }
    
            if (Contenido != null)
            {
                if (!Contenido.Megusta.Contains(this))
                {
                    Contenido.Megusta.Add(this);
                }
                if (ContenidoId != Contenido.Id)
                {
                    ContenidoId = Contenido.Id;
                }
            }
        }
    
        private void FixupEspecificacionUsuario(EspecificacionUsuario previousValue)
        {
            if (previousValue != null && previousValue.Megusta.Contains(this))
            {
                previousValue.Megusta.Remove(this);
            }
    
            if (EspecificacionUsuario != null)
            {
                if (!EspecificacionUsuario.Megusta.Contains(this))
                {
                    EspecificacionUsuario.Megusta.Add(this);
                }
                if (EspecificacionUsuarioId != EspecificacionUsuario.Id)
                {
                    EspecificacionUsuarioId = EspecificacionUsuario.Id;
                }
            }
        }

        #endregion
    }
}
