//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace IndignadoFramework.Entities
{
    [Serializable]
    [DataContractAttribute(IsReference = true)]
    [KnownType(typeof(MensajeChatProjection))]
    [MetadataType(typeof(MensajeChatMetaData))]
    public partial class MensajeChat 
    {
        #region Primitive Properties
    
        [DataMemberAttribute()]
        public virtual int idRoom
        {
            get;
            set;
        }
    
        [DataMemberAttribute()]
        public virtual string idMensaje
        {
            get;
            set;
        }
    
        [DataMemberAttribute()]
        public virtual Nullable<System.DateTime> fecha
        {
            get;
            set;
        }
    
        [DataMemberAttribute()]
        public virtual string mensaje
        {
            get;
            set;
        }
    
        [DataMemberAttribute()]
        public virtual Nullable<int> usuarioId
        {
            get;
            set;
        }
    
        [DataMemberAttribute()]
        public virtual string usuarioNombre
        {
            get;
            set;
        }

        #endregion
    }
}
