//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace IndignadoFramework.Entities
{
    
    
    public class MensajeChatMetaData
    {
    	[Display(Name ="idRoom")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int idRoom { get; set; }
    	
    	[Display(Name ="idMensaje")]
    	[StringLength(195, ErrorMessage="Debe ingresar menos de 195 caracteres")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual string idMensaje { get; set; }
    	
    	[Display(Name ="fecha")]
        public virtual Nullable<System.DateTime> fecha { get; set; }
    	
    	[Display(Name ="mensaje")]
        public virtual string mensaje { get; set; }
    	
    	[Display(Name ="usuarioId")]
        public virtual Nullable<int> usuarioId { get; set; }
    	
    	[Display(Name ="usuarioNombre")]
        public virtual string usuarioNombre { get; set; }
    	
    }
}
