//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace IndignadoFramework.Entities
{
    
    
    public class MovimientoMetaData
    {
    	[Display(Name ="Id")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int Id { get; set; }
    	
    	[Display(Name ="Nombre")]
    	[StringLength(45, ErrorMessage="Debe ingresar menos de 45 caracteres")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual string Nombre { get; set; }
    	
    	[Display(Name ="UbicacionLatitud")]
        public virtual Nullable<double> UbicacionLatitud { get; set; }
    	
    	[Display(Name ="UbicacionLongitud")]
        public virtual Nullable<double> UbicacionLongitud { get; set; }
    	
    	[Display(Name ="Descripcion")]
        public virtual string Descripcion { get; set; }
    	
    	[Display(Name ="Logo")]
        public virtual string Logo { get; set; }
    	
    	[Display(Name ="Estilo")]
        public virtual string Estilo { get; set; }
    	
    	[Display(Name ="M")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int M { get; set; }
    	
    	[Display(Name ="N")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int N { get; set; }
    	
    	[Display(Name ="X")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int X { get; set; }
    	
    	[Display(Name ="Z")]
        [Required(ErrorMessage="Campo requerido")]
        public virtual int Z { get; set; }
    	
    }
}
