//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignadoFramework.UI.Mvc4.BackOffice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProcessExecutionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackOffice.IBackOfficeService")]
    public interface IBackOfficeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/GetHello", ReplyAction="http://tempuri.org/IBackOfficeService/GetHelloResponse")]
        string GetHello();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/GetHello", ReplyAction="http://tempuri.org/IBackOfficeService/GetHelloResponse")]
        System.IAsyncResult BeginGetHello(System.AsyncCallback callback, object asyncState);
        
        string EndGetHello(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/AgregarFuente", ReplyAction="http://tempuri.org/IBackOfficeService/AgregarFuenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/AgregarFuenteProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.FuenteWEBProjection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        void AgregarFuente(IndignadoFramework.Entities.FuenteWEB fuente);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/AgregarFuente", ReplyAction="http://tempuri.org/IBackOfficeService/AgregarFuenteResponse")]
        System.IAsyncResult BeginAgregarFuente(IndignadoFramework.Entities.FuenteWEB fuente, System.AsyncCallback callback, object asyncState);
        
        void EndAgregarFuente(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientos", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientosProcessExecutionFaul" +
            "tFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Movimiento[] ObtenerTodosMovimientos();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientos", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientosResponse")]
        System.IAsyncResult BeginObtenerTodosMovimientos(System.AsyncCallback callback, object asyncState);
        
        IndignadoFramework.Entities.Movimiento[] EndObtenerTodosMovimientos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/AgregarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/AgregarMovimientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/AgregarMovimientoProcessExecutionFaultFault" +
            "", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento AgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/AgregarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/AgregarMovimientoResponse")]
        System.IAsyncResult BeginAgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento, System.AsyncCallback callback, object asyncState);
        
        IndignadoFramework.Entities.Movimiento EndAgregarMovimiento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/BorrarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/BorrarMovimientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/BorrarMovimientoProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        void BorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/BorrarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/BorrarMovimientoResponse")]
        System.IAsyncResult BeginBorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento, System.AsyncCallback callback, object asyncState);
        
        void EndBorrarMovimiento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ModificarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/ModificarMovimientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ModificarMovimientoProcessExecutionFaultFau" +
            "lt", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        void ModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/ModificarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/ModificarMovimientoResponse")]
        System.IAsyncResult BeginModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento, System.AsyncCallback callback, object asyncState);
        
        void EndModificarMovimiento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombre", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombreProcessExecutionFau" +
            "ltFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento ObtenerMovimientoXNombre(string nombreMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombre", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombreResponse")]
        System.IAsyncResult BeginObtenerMovimientoXNombre(string nombreMovimiento, System.AsyncCallback callback, object asyncState);
        
        IndignadoFramework.Entities.Movimiento EndObtenerMovimientoXNombre(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXId", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXIdProcessExecutionFaultFa" +
            "ult", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento ObtenerMovimientoXId(int idMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXId", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXIdResponse")]
        System.IAsyncResult BeginObtenerMovimientoXId(int idMovimiento, System.AsyncCallback callback, object asyncState);
        
        IndignadoFramework.Entities.Movimiento EndObtenerMovimientoXId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginando", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginandoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginandoProcessExecution" +
            "FaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Movimiento[] ObtenerMovimientosPaginando(int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginando", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginandoResponse")]
        System.IAsyncResult BeginObtenerMovimientosPaginando(int pageNumber, int pageSize, System.AsyncCallback callback, object asyncState);
        
        IndignadoFramework.Entities.Movimiento[] EndObtenerMovimientosPaginando(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerContenidosMovimientoPorInadecuado", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerContenidosMovimientoPorInadecuadoRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerContenidosMovimientoPorInadecuadoPro" +
            "cessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Contenido[] ObtenerContenidosMovimientoPorInadecuado(int idMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/ObtenerContenidosMovimientoPorInadecuado", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerContenidosMovimientoPorInadecuadoRes" +
            "ponse")]
        System.IAsyncResult BeginObtenerContenidosMovimientoPorInadecuado(int idMovimiento, System.AsyncCallback callback, object asyncState);
        
        IndignadoFramework.Entities.Contenido[] EndObtenerContenidosMovimientoPorInadecuado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/EliminarEspecificacionUsuario", ReplyAction="http://tempuri.org/IBackOfficeService/EliminarEspecificacionUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UI.Mvc4.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/EliminarEspecificacionUsuarioProcessExecuti" +
            "onFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        void EliminarEspecificacionUsuario(int idus);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBackOfficeService/EliminarEspecificacionUsuario", ReplyAction="http://tempuri.org/IBackOfficeService/EliminarEspecificacionUsuarioResponse")]
        System.IAsyncResult BeginEliminarEspecificacionUsuario(int idus, System.AsyncCallback callback, object asyncState);
        
        void EndEliminarEspecificacionUsuario(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackOfficeServiceChannel : IndignadoFramework.UI.Mvc4.BackOffice.IBackOfficeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerTodosMovimientosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerTodosMovimientosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndignadoFramework.Entities.Movimiento[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndignadoFramework.Entities.Movimiento[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarMovimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AgregarMovimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndignadoFramework.Entities.Movimiento Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndignadoFramework.Entities.Movimiento)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerMovimientoXNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerMovimientoXNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndignadoFramework.Entities.Movimiento Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndignadoFramework.Entities.Movimiento)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerMovimientoXIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerMovimientoXIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndignadoFramework.Entities.Movimiento Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndignadoFramework.Entities.Movimiento)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerMovimientosPaginandoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerMovimientosPaginandoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndignadoFramework.Entities.Movimiento[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndignadoFramework.Entities.Movimiento[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerContenidosMovimientoPorInadecuadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerContenidosMovimientoPorInadecuadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public IndignadoFramework.Entities.Contenido[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((IndignadoFramework.Entities.Contenido[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackOfficeServiceClient : System.ServiceModel.ClientBase<IndignadoFramework.UI.Mvc4.BackOffice.IBackOfficeService>, IndignadoFramework.UI.Mvc4.BackOffice.IBackOfficeService {
        
        private BeginOperationDelegate onBeginGetHelloDelegate;
        
        private EndOperationDelegate onEndGetHelloDelegate;
        
        private System.Threading.SendOrPostCallback onGetHelloCompletedDelegate;
        
        private BeginOperationDelegate onBeginAgregarFuenteDelegate;
        
        private EndOperationDelegate onEndAgregarFuenteDelegate;
        
        private System.Threading.SendOrPostCallback onAgregarFuenteCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerTodosMovimientosDelegate;
        
        private EndOperationDelegate onEndObtenerTodosMovimientosDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerTodosMovimientosCompletedDelegate;
        
        private BeginOperationDelegate onBeginAgregarMovimientoDelegate;
        
        private EndOperationDelegate onEndAgregarMovimientoDelegate;
        
        private System.Threading.SendOrPostCallback onAgregarMovimientoCompletedDelegate;
        
        private BeginOperationDelegate onBeginBorrarMovimientoDelegate;
        
        private EndOperationDelegate onEndBorrarMovimientoDelegate;
        
        private System.Threading.SendOrPostCallback onBorrarMovimientoCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificarMovimientoDelegate;
        
        private EndOperationDelegate onEndModificarMovimientoDelegate;
        
        private System.Threading.SendOrPostCallback onModificarMovimientoCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerMovimientoXNombreDelegate;
        
        private EndOperationDelegate onEndObtenerMovimientoXNombreDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerMovimientoXNombreCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerMovimientoXIdDelegate;
        
        private EndOperationDelegate onEndObtenerMovimientoXIdDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerMovimientoXIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerMovimientosPaginandoDelegate;
        
        private EndOperationDelegate onEndObtenerMovimientosPaginandoDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerMovimientosPaginandoCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerContenidosMovimientoPorInadecuadoDelegate;
        
        private EndOperationDelegate onEndObtenerContenidosMovimientoPorInadecuadoDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerContenidosMovimientoPorInadecuadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarEspecificacionUsuarioDelegate;
        
        private EndOperationDelegate onEndEliminarEspecificacionUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarEspecificacionUsuarioCompletedDelegate;
        
        public BackOfficeServiceClient() {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetHelloCompletedEventArgs> GetHelloCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AgregarFuenteCompleted;
        
        public event System.EventHandler<ObtenerTodosMovimientosCompletedEventArgs> ObtenerTodosMovimientosCompleted;
        
        public event System.EventHandler<AgregarMovimientoCompletedEventArgs> AgregarMovimientoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> BorrarMovimientoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ModificarMovimientoCompleted;
        
        public event System.EventHandler<ObtenerMovimientoXNombreCompletedEventArgs> ObtenerMovimientoXNombreCompleted;
        
        public event System.EventHandler<ObtenerMovimientoXIdCompletedEventArgs> ObtenerMovimientoXIdCompleted;
        
        public event System.EventHandler<ObtenerMovimientosPaginandoCompletedEventArgs> ObtenerMovimientosPaginandoCompleted;
        
        public event System.EventHandler<ObtenerContenidosMovimientoPorInadecuadoCompletedEventArgs> ObtenerContenidosMovimientoPorInadecuadoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EliminarEspecificacionUsuarioCompleted;
        
        public string GetHello() {
            return base.Channel.GetHello();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetHello(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHello(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetHello(System.IAsyncResult result) {
            return base.Channel.EndGetHello(result);
        }
        
        private System.IAsyncResult OnBeginGetHello(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetHello(callback, asyncState);
        }
        
        private object[] OnEndGetHello(System.IAsyncResult result) {
            string retVal = this.EndGetHello(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHelloCompleted(object state) {
            if ((this.GetHelloCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHelloCompleted(this, new GetHelloCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHelloAsync() {
            this.GetHelloAsync(null);
        }
        
        public void GetHelloAsync(object userState) {
            if ((this.onBeginGetHelloDelegate == null)) {
                this.onBeginGetHelloDelegate = new BeginOperationDelegate(this.OnBeginGetHello);
            }
            if ((this.onEndGetHelloDelegate == null)) {
                this.onEndGetHelloDelegate = new EndOperationDelegate(this.OnEndGetHello);
            }
            if ((this.onGetHelloCompletedDelegate == null)) {
                this.onGetHelloCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHelloCompleted);
            }
            base.InvokeAsync(this.onBeginGetHelloDelegate, null, this.onEndGetHelloDelegate, this.onGetHelloCompletedDelegate, userState);
        }
        
        public void AgregarFuente(IndignadoFramework.Entities.FuenteWEB fuente) {
            base.Channel.AgregarFuente(fuente);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAgregarFuente(IndignadoFramework.Entities.FuenteWEB fuente, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAgregarFuente(fuente, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAgregarFuente(System.IAsyncResult result) {
            base.Channel.EndAgregarFuente(result);
        }
        
        private System.IAsyncResult OnBeginAgregarFuente(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndignadoFramework.Entities.FuenteWEB fuente = ((IndignadoFramework.Entities.FuenteWEB)(inValues[0]));
            return this.BeginAgregarFuente(fuente, callback, asyncState);
        }
        
        private object[] OnEndAgregarFuente(System.IAsyncResult result) {
            this.EndAgregarFuente(result);
            return null;
        }
        
        private void OnAgregarFuenteCompleted(object state) {
            if ((this.AgregarFuenteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AgregarFuenteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AgregarFuenteAsync(IndignadoFramework.Entities.FuenteWEB fuente) {
            this.AgregarFuenteAsync(fuente, null);
        }
        
        public void AgregarFuenteAsync(IndignadoFramework.Entities.FuenteWEB fuente, object userState) {
            if ((this.onBeginAgregarFuenteDelegate == null)) {
                this.onBeginAgregarFuenteDelegate = new BeginOperationDelegate(this.OnBeginAgregarFuente);
            }
            if ((this.onEndAgregarFuenteDelegate == null)) {
                this.onEndAgregarFuenteDelegate = new EndOperationDelegate(this.OnEndAgregarFuente);
            }
            if ((this.onAgregarFuenteCompletedDelegate == null)) {
                this.onAgregarFuenteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAgregarFuenteCompleted);
            }
            base.InvokeAsync(this.onBeginAgregarFuenteDelegate, new object[] {
                        fuente}, this.onEndAgregarFuenteDelegate, this.onAgregarFuenteCompletedDelegate, userState);
        }
        
        public IndignadoFramework.Entities.Movimiento[] ObtenerTodosMovimientos() {
            return base.Channel.ObtenerTodosMovimientos();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerTodosMovimientos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerTodosMovimientos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public IndignadoFramework.Entities.Movimiento[] EndObtenerTodosMovimientos(System.IAsyncResult result) {
            return base.Channel.EndObtenerTodosMovimientos(result);
        }
        
        private System.IAsyncResult OnBeginObtenerTodosMovimientos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginObtenerTodosMovimientos(callback, asyncState);
        }
        
        private object[] OnEndObtenerTodosMovimientos(System.IAsyncResult result) {
            IndignadoFramework.Entities.Movimiento[] retVal = this.EndObtenerTodosMovimientos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerTodosMovimientosCompleted(object state) {
            if ((this.ObtenerTodosMovimientosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerTodosMovimientosCompleted(this, new ObtenerTodosMovimientosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerTodosMovimientosAsync() {
            this.ObtenerTodosMovimientosAsync(null);
        }
        
        public void ObtenerTodosMovimientosAsync(object userState) {
            if ((this.onBeginObtenerTodosMovimientosDelegate == null)) {
                this.onBeginObtenerTodosMovimientosDelegate = new BeginOperationDelegate(this.OnBeginObtenerTodosMovimientos);
            }
            if ((this.onEndObtenerTodosMovimientosDelegate == null)) {
                this.onEndObtenerTodosMovimientosDelegate = new EndOperationDelegate(this.OnEndObtenerTodosMovimientos);
            }
            if ((this.onObtenerTodosMovimientosCompletedDelegate == null)) {
                this.onObtenerTodosMovimientosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerTodosMovimientosCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerTodosMovimientosDelegate, null, this.onEndObtenerTodosMovimientosDelegate, this.onObtenerTodosMovimientosCompletedDelegate, userState);
        }
        
        public IndignadoFramework.Entities.Movimiento AgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            return base.Channel.AgregarMovimiento(movimiento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAgregarMovimiento(movimiento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public IndignadoFramework.Entities.Movimiento EndAgregarMovimiento(System.IAsyncResult result) {
            return base.Channel.EndAgregarMovimiento(result);
        }
        
        private System.IAsyncResult OnBeginAgregarMovimiento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndignadoFramework.Entities.Movimiento movimiento = ((IndignadoFramework.Entities.Movimiento)(inValues[0]));
            return this.BeginAgregarMovimiento(movimiento, callback, asyncState);
        }
        
        private object[] OnEndAgregarMovimiento(System.IAsyncResult result) {
            IndignadoFramework.Entities.Movimiento retVal = this.EndAgregarMovimiento(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAgregarMovimientoCompleted(object state) {
            if ((this.AgregarMovimientoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AgregarMovimientoCompleted(this, new AgregarMovimientoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AgregarMovimientoAsync(IndignadoFramework.Entities.Movimiento movimiento) {
            this.AgregarMovimientoAsync(movimiento, null);
        }
        
        public void AgregarMovimientoAsync(IndignadoFramework.Entities.Movimiento movimiento, object userState) {
            if ((this.onBeginAgregarMovimientoDelegate == null)) {
                this.onBeginAgregarMovimientoDelegate = new BeginOperationDelegate(this.OnBeginAgregarMovimiento);
            }
            if ((this.onEndAgregarMovimientoDelegate == null)) {
                this.onEndAgregarMovimientoDelegate = new EndOperationDelegate(this.OnEndAgregarMovimiento);
            }
            if ((this.onAgregarMovimientoCompletedDelegate == null)) {
                this.onAgregarMovimientoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAgregarMovimientoCompleted);
            }
            base.InvokeAsync(this.onBeginAgregarMovimientoDelegate, new object[] {
                        movimiento}, this.onEndAgregarMovimientoDelegate, this.onAgregarMovimientoCompletedDelegate, userState);
        }
        
        public void BorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            base.Channel.BorrarMovimiento(movimiento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginBorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBorrarMovimiento(movimiento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndBorrarMovimiento(System.IAsyncResult result) {
            base.Channel.EndBorrarMovimiento(result);
        }
        
        private System.IAsyncResult OnBeginBorrarMovimiento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndignadoFramework.Entities.Movimiento movimiento = ((IndignadoFramework.Entities.Movimiento)(inValues[0]));
            return this.BeginBorrarMovimiento(movimiento, callback, asyncState);
        }
        
        private object[] OnEndBorrarMovimiento(System.IAsyncResult result) {
            this.EndBorrarMovimiento(result);
            return null;
        }
        
        private void OnBorrarMovimientoCompleted(object state) {
            if ((this.BorrarMovimientoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BorrarMovimientoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BorrarMovimientoAsync(IndignadoFramework.Entities.Movimiento movimiento) {
            this.BorrarMovimientoAsync(movimiento, null);
        }
        
        public void BorrarMovimientoAsync(IndignadoFramework.Entities.Movimiento movimiento, object userState) {
            if ((this.onBeginBorrarMovimientoDelegate == null)) {
                this.onBeginBorrarMovimientoDelegate = new BeginOperationDelegate(this.OnBeginBorrarMovimiento);
            }
            if ((this.onEndBorrarMovimientoDelegate == null)) {
                this.onEndBorrarMovimientoDelegate = new EndOperationDelegate(this.OnEndBorrarMovimiento);
            }
            if ((this.onBorrarMovimientoCompletedDelegate == null)) {
                this.onBorrarMovimientoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBorrarMovimientoCompleted);
            }
            base.InvokeAsync(this.onBeginBorrarMovimientoDelegate, new object[] {
                        movimiento}, this.onEndBorrarMovimientoDelegate, this.onBorrarMovimientoCompletedDelegate, userState);
        }
        
        public void ModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            base.Channel.ModificarMovimiento(movimiento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificarMovimiento(movimiento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndModificarMovimiento(System.IAsyncResult result) {
            base.Channel.EndModificarMovimiento(result);
        }
        
        private System.IAsyncResult OnBeginModificarMovimiento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            IndignadoFramework.Entities.Movimiento movimiento = ((IndignadoFramework.Entities.Movimiento)(inValues[0]));
            return this.BeginModificarMovimiento(movimiento, callback, asyncState);
        }
        
        private object[] OnEndModificarMovimiento(System.IAsyncResult result) {
            this.EndModificarMovimiento(result);
            return null;
        }
        
        private void OnModificarMovimientoCompleted(object state) {
            if ((this.ModificarMovimientoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ModificarMovimientoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ModificarMovimientoAsync(IndignadoFramework.Entities.Movimiento movimiento) {
            this.ModificarMovimientoAsync(movimiento, null);
        }
        
        public void ModificarMovimientoAsync(IndignadoFramework.Entities.Movimiento movimiento, object userState) {
            if ((this.onBeginModificarMovimientoDelegate == null)) {
                this.onBeginModificarMovimientoDelegate = new BeginOperationDelegate(this.OnBeginModificarMovimiento);
            }
            if ((this.onEndModificarMovimientoDelegate == null)) {
                this.onEndModificarMovimientoDelegate = new EndOperationDelegate(this.OnEndModificarMovimiento);
            }
            if ((this.onModificarMovimientoCompletedDelegate == null)) {
                this.onModificarMovimientoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificarMovimientoCompleted);
            }
            base.InvokeAsync(this.onBeginModificarMovimientoDelegate, new object[] {
                        movimiento}, this.onEndModificarMovimientoDelegate, this.onModificarMovimientoCompletedDelegate, userState);
        }
        
        public IndignadoFramework.Entities.Movimiento ObtenerMovimientoXNombre(string nombreMovimiento) {
            return base.Channel.ObtenerMovimientoXNombre(nombreMovimiento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerMovimientoXNombre(string nombreMovimiento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerMovimientoXNombre(nombreMovimiento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public IndignadoFramework.Entities.Movimiento EndObtenerMovimientoXNombre(System.IAsyncResult result) {
            return base.Channel.EndObtenerMovimientoXNombre(result);
        }
        
        private System.IAsyncResult OnBeginObtenerMovimientoXNombre(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nombreMovimiento = ((string)(inValues[0]));
            return this.BeginObtenerMovimientoXNombre(nombreMovimiento, callback, asyncState);
        }
        
        private object[] OnEndObtenerMovimientoXNombre(System.IAsyncResult result) {
            IndignadoFramework.Entities.Movimiento retVal = this.EndObtenerMovimientoXNombre(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerMovimientoXNombreCompleted(object state) {
            if ((this.ObtenerMovimientoXNombreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerMovimientoXNombreCompleted(this, new ObtenerMovimientoXNombreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerMovimientoXNombreAsync(string nombreMovimiento) {
            this.ObtenerMovimientoXNombreAsync(nombreMovimiento, null);
        }
        
        public void ObtenerMovimientoXNombreAsync(string nombreMovimiento, object userState) {
            if ((this.onBeginObtenerMovimientoXNombreDelegate == null)) {
                this.onBeginObtenerMovimientoXNombreDelegate = new BeginOperationDelegate(this.OnBeginObtenerMovimientoXNombre);
            }
            if ((this.onEndObtenerMovimientoXNombreDelegate == null)) {
                this.onEndObtenerMovimientoXNombreDelegate = new EndOperationDelegate(this.OnEndObtenerMovimientoXNombre);
            }
            if ((this.onObtenerMovimientoXNombreCompletedDelegate == null)) {
                this.onObtenerMovimientoXNombreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerMovimientoXNombreCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerMovimientoXNombreDelegate, new object[] {
                        nombreMovimiento}, this.onEndObtenerMovimientoXNombreDelegate, this.onObtenerMovimientoXNombreCompletedDelegate, userState);
        }
        
        public IndignadoFramework.Entities.Movimiento ObtenerMovimientoXId(int idMovimiento) {
            return base.Channel.ObtenerMovimientoXId(idMovimiento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerMovimientoXId(int idMovimiento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerMovimientoXId(idMovimiento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public IndignadoFramework.Entities.Movimiento EndObtenerMovimientoXId(System.IAsyncResult result) {
            return base.Channel.EndObtenerMovimientoXId(result);
        }
        
        private System.IAsyncResult OnBeginObtenerMovimientoXId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idMovimiento = ((int)(inValues[0]));
            return this.BeginObtenerMovimientoXId(idMovimiento, callback, asyncState);
        }
        
        private object[] OnEndObtenerMovimientoXId(System.IAsyncResult result) {
            IndignadoFramework.Entities.Movimiento retVal = this.EndObtenerMovimientoXId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerMovimientoXIdCompleted(object state) {
            if ((this.ObtenerMovimientoXIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerMovimientoXIdCompleted(this, new ObtenerMovimientoXIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerMovimientoXIdAsync(int idMovimiento) {
            this.ObtenerMovimientoXIdAsync(idMovimiento, null);
        }
        
        public void ObtenerMovimientoXIdAsync(int idMovimiento, object userState) {
            if ((this.onBeginObtenerMovimientoXIdDelegate == null)) {
                this.onBeginObtenerMovimientoXIdDelegate = new BeginOperationDelegate(this.OnBeginObtenerMovimientoXId);
            }
            if ((this.onEndObtenerMovimientoXIdDelegate == null)) {
                this.onEndObtenerMovimientoXIdDelegate = new EndOperationDelegate(this.OnEndObtenerMovimientoXId);
            }
            if ((this.onObtenerMovimientoXIdCompletedDelegate == null)) {
                this.onObtenerMovimientoXIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerMovimientoXIdCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerMovimientoXIdDelegate, new object[] {
                        idMovimiento}, this.onEndObtenerMovimientoXIdDelegate, this.onObtenerMovimientoXIdCompletedDelegate, userState);
        }
        
        public IndignadoFramework.Entities.Movimiento[] ObtenerMovimientosPaginando(int pageNumber, int pageSize) {
            return base.Channel.ObtenerMovimientosPaginando(pageNumber, pageSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerMovimientosPaginando(int pageNumber, int pageSize, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerMovimientosPaginando(pageNumber, pageSize, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public IndignadoFramework.Entities.Movimiento[] EndObtenerMovimientosPaginando(System.IAsyncResult result) {
            return base.Channel.EndObtenerMovimientosPaginando(result);
        }
        
        private System.IAsyncResult OnBeginObtenerMovimientosPaginando(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageNumber = ((int)(inValues[0]));
            int pageSize = ((int)(inValues[1]));
            return this.BeginObtenerMovimientosPaginando(pageNumber, pageSize, callback, asyncState);
        }
        
        private object[] OnEndObtenerMovimientosPaginando(System.IAsyncResult result) {
            IndignadoFramework.Entities.Movimiento[] retVal = this.EndObtenerMovimientosPaginando(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerMovimientosPaginandoCompleted(object state) {
            if ((this.ObtenerMovimientosPaginandoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerMovimientosPaginandoCompleted(this, new ObtenerMovimientosPaginandoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerMovimientosPaginandoAsync(int pageNumber, int pageSize) {
            this.ObtenerMovimientosPaginandoAsync(pageNumber, pageSize, null);
        }
        
        public void ObtenerMovimientosPaginandoAsync(int pageNumber, int pageSize, object userState) {
            if ((this.onBeginObtenerMovimientosPaginandoDelegate == null)) {
                this.onBeginObtenerMovimientosPaginandoDelegate = new BeginOperationDelegate(this.OnBeginObtenerMovimientosPaginando);
            }
            if ((this.onEndObtenerMovimientosPaginandoDelegate == null)) {
                this.onEndObtenerMovimientosPaginandoDelegate = new EndOperationDelegate(this.OnEndObtenerMovimientosPaginando);
            }
            if ((this.onObtenerMovimientosPaginandoCompletedDelegate == null)) {
                this.onObtenerMovimientosPaginandoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerMovimientosPaginandoCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerMovimientosPaginandoDelegate, new object[] {
                        pageNumber,
                        pageSize}, this.onEndObtenerMovimientosPaginandoDelegate, this.onObtenerMovimientosPaginandoCompletedDelegate, userState);
        }
        
        public IndignadoFramework.Entities.Contenido[] ObtenerContenidosMovimientoPorInadecuado(int idMovimiento) {
            return base.Channel.ObtenerContenidosMovimientoPorInadecuado(idMovimiento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerContenidosMovimientoPorInadecuado(int idMovimiento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerContenidosMovimientoPorInadecuado(idMovimiento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public IndignadoFramework.Entities.Contenido[] EndObtenerContenidosMovimientoPorInadecuado(System.IAsyncResult result) {
            return base.Channel.EndObtenerContenidosMovimientoPorInadecuado(result);
        }
        
        private System.IAsyncResult OnBeginObtenerContenidosMovimientoPorInadecuado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idMovimiento = ((int)(inValues[0]));
            return this.BeginObtenerContenidosMovimientoPorInadecuado(idMovimiento, callback, asyncState);
        }
        
        private object[] OnEndObtenerContenidosMovimientoPorInadecuado(System.IAsyncResult result) {
            IndignadoFramework.Entities.Contenido[] retVal = this.EndObtenerContenidosMovimientoPorInadecuado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerContenidosMovimientoPorInadecuadoCompleted(object state) {
            if ((this.ObtenerContenidosMovimientoPorInadecuadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerContenidosMovimientoPorInadecuadoCompleted(this, new ObtenerContenidosMovimientoPorInadecuadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerContenidosMovimientoPorInadecuadoAsync(int idMovimiento) {
            this.ObtenerContenidosMovimientoPorInadecuadoAsync(idMovimiento, null);
        }
        
        public void ObtenerContenidosMovimientoPorInadecuadoAsync(int idMovimiento, object userState) {
            if ((this.onBeginObtenerContenidosMovimientoPorInadecuadoDelegate == null)) {
                this.onBeginObtenerContenidosMovimientoPorInadecuadoDelegate = new BeginOperationDelegate(this.OnBeginObtenerContenidosMovimientoPorInadecuado);
            }
            if ((this.onEndObtenerContenidosMovimientoPorInadecuadoDelegate == null)) {
                this.onEndObtenerContenidosMovimientoPorInadecuadoDelegate = new EndOperationDelegate(this.OnEndObtenerContenidosMovimientoPorInadecuado);
            }
            if ((this.onObtenerContenidosMovimientoPorInadecuadoCompletedDelegate == null)) {
                this.onObtenerContenidosMovimientoPorInadecuadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerContenidosMovimientoPorInadecuadoCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerContenidosMovimientoPorInadecuadoDelegate, new object[] {
                        idMovimiento}, this.onEndObtenerContenidosMovimientoPorInadecuadoDelegate, this.onObtenerContenidosMovimientoPorInadecuadoCompletedDelegate, userState);
        }
        
        public void EliminarEspecificacionUsuario(int idus) {
            base.Channel.EliminarEspecificacionUsuario(idus);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEliminarEspecificacionUsuario(int idus, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarEspecificacionUsuario(idus, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndEliminarEspecificacionUsuario(System.IAsyncResult result) {
            base.Channel.EndEliminarEspecificacionUsuario(result);
        }
        
        private System.IAsyncResult OnBeginEliminarEspecificacionUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idus = ((int)(inValues[0]));
            return this.BeginEliminarEspecificacionUsuario(idus, callback, asyncState);
        }
        
        private object[] OnEndEliminarEspecificacionUsuario(System.IAsyncResult result) {
            this.EndEliminarEspecificacionUsuario(result);
            return null;
        }
        
        private void OnEliminarEspecificacionUsuarioCompleted(object state) {
            if ((this.EliminarEspecificacionUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarEspecificacionUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarEspecificacionUsuarioAsync(int idus) {
            this.EliminarEspecificacionUsuarioAsync(idus, null);
        }
        
        public void EliminarEspecificacionUsuarioAsync(int idus, object userState) {
            if ((this.onBeginEliminarEspecificacionUsuarioDelegate == null)) {
                this.onBeginEliminarEspecificacionUsuarioDelegate = new BeginOperationDelegate(this.OnBeginEliminarEspecificacionUsuario);
            }
            if ((this.onEndEliminarEspecificacionUsuarioDelegate == null)) {
                this.onEndEliminarEspecificacionUsuarioDelegate = new EndOperationDelegate(this.OnEndEliminarEspecificacionUsuario);
            }
            if ((this.onEliminarEspecificacionUsuarioCompletedDelegate == null)) {
                this.onEliminarEspecificacionUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarEspecificacionUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarEspecificacionUsuarioDelegate, new object[] {
                        idus}, this.onEndEliminarEspecificacionUsuarioDelegate, this.onEliminarEspecificacionUsuarioCompletedDelegate, userState);
        }
    }
}
