//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using IndignadoFramework.Entities;

namespace IndignadoFramework.Data
{
    public partial class ContextoIndignadoFramework : ObjectContext
    {
        public const string ConnectionString = "name=ContextoIndignadoFramework";
        public const string ContainerName = "ContextoIndignadoFramework";
    
        #region Constructors
    
        public ContextoIndignadoFramework()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public ContextoIndignadoFramework(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public ContextoIndignadoFramework(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Movimiento> MovimientoSet
        {
            get { return _movimientoSet  ?? (_movimientoSet = CreateObjectSet<Movimiento>("MovimientoSet")); }
        }
        private ObjectSet<Movimiento> _movimientoSet;
    
        public ObjectSet<Convocatoria> ConvocatoriaSet
        {
            get { return _convocatoriaSet  ?? (_convocatoriaSet = CreateObjectSet<Convocatoria>("ConvocatoriaSet")); }
        }
        private ObjectSet<Convocatoria> _convocatoriaSet;
    
        public ObjectSet<EspecificacionUsuario> EspecificacionUsuarioSet
        {
            get { return _especificacionUsuarioSet  ?? (_especificacionUsuarioSet = CreateObjectSet<EspecificacionUsuario>("EspecificacionUsuarioSet")); }
        }
        private ObjectSet<EspecificacionUsuario> _especificacionUsuarioSet;
    
        public ObjectSet<CategoriaTematica> CategoriaTematicaSet
        {
            get { return _categoriaTematicaSet  ?? (_categoriaTematicaSet = CreateObjectSet<CategoriaTematica>("CategoriaTematicaSet")); }
        }
        private ObjectSet<CategoriaTematica> _categoriaTematicaSet;
    
        public ObjectSet<Contenido> ContenidoSet
        {
            get { return _contenidoSet  ?? (_contenidoSet = CreateObjectSet<Contenido>("ContenidoSet")); }
        }
        private ObjectSet<Contenido> _contenidoSet;
    
        public ObjectSet<FuenteWEB> FuenteWEBSet
        {
            get { return _fuenteWEBSet  ?? (_fuenteWEBSet = CreateObjectSet<FuenteWEB>("FuenteWEBSet")); }
        }
        private ObjectSet<FuenteWEB> _fuenteWEBSet;
    
        public ObjectSet<Megusta> MegustaSet
        {
            get { return _megustaSet  ?? (_megustaSet = CreateObjectSet<Megusta>("MegustaSet")); }
        }
        private ObjectSet<Megusta> _megustaSet;
    
        public ObjectSet<MensajeChat> MensajeChatSet
        {
            get { return _mensajeChatSet  ?? (_mensajeChatSet = CreateObjectSet<MensajeChat>("MensajeChatSet")); }
        }
        private ObjectSet<MensajeChat> _mensajeChatSet;

        #endregion
    }
}
