//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTest.BackOffice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProcessExecutionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackOffice.IBackOfficeService")]
    public interface IBackOfficeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/GetHello", ReplyAction="http://tempuri.org/IBackOfficeService/GetHelloResponse")]
        string GetHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientos", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusinessTest.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerTodosMovimientosProcessExecutionFaul" +
            "tFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Movimiento[] ObtenerTodosMovimientos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/AgregarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/AgregarMovimientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusinessTest.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/AgregarMovimientoProcessExecutionFaultFault" +
            "", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento AgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/BorrarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/BorrarMovimientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusinessTest.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/BorrarMovimientoProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        void BorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ModificarMovimiento", ReplyAction="http://tempuri.org/IBackOfficeService/ModificarMovimientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusinessTest.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ModificarMovimientoProcessExecutionFaultFau" +
            "lt", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        void ModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombre", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusinessTest.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXNombreProcessExecutionFau" +
            "ltFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento ObtenerMovimientoXNombre(string nombreMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXId", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusinessTest.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientoXIdProcessExecutionFaultFa" +
            "ult", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento ObtenerMovimientoXId(int idMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginando", ReplyAction="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginandoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BusinessTest.BackOffice.ProcessExecutionFault), Action="http://tempuri.org/IBackOfficeService/ObtenerMovimientosPaginandoProcessExecution" +
            "FaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Movimiento[] ObtenerMovimientosPaginando(int pageNumber, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackOfficeServiceChannel : BusinessTest.BackOffice.IBackOfficeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackOfficeServiceClient : System.ServiceModel.ClientBase<BusinessTest.BackOffice.IBackOfficeService>, BusinessTest.BackOffice.IBackOfficeService {
        
        public BackOfficeServiceClient() {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHello() {
            return base.Channel.GetHello();
        }
        
        public IndignadoFramework.Entities.Movimiento[] ObtenerTodosMovimientos() {
            return base.Channel.ObtenerTodosMovimientos();
        }
        
        public IndignadoFramework.Entities.Movimiento AgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            return base.Channel.AgregarMovimiento(movimiento);
        }
        
        public void BorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            base.Channel.BorrarMovimiento(movimiento);
        }
        
        public void ModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            base.Channel.ModificarMovimiento(movimiento);
        }
        
        public IndignadoFramework.Entities.Movimiento ObtenerMovimientoXNombre(string nombreMovimiento) {
            return base.Channel.ObtenerMovimientoXNombre(nombreMovimiento);
        }
        
        public IndignadoFramework.Entities.Movimiento ObtenerMovimientoXId(int idMovimiento) {
            return base.Channel.ObtenerMovimientoXId(idMovimiento);
        }
        
        public IndignadoFramework.Entities.Movimiento[] ObtenerMovimientosPaginando(int pageNumber, int pageSize) {
            return base.Channel.ObtenerMovimientosPaginando(pageNumber, pageSize);
        }
    }
}
