//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignadoFramework.UIProcess.BackOfficeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProcessExecutionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serena-yeoh//LayerSample/Expense/2007/08", ConfigurationName="BackOfficeService.IBackOfficeService")]
    public interface IBackOfficeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerTodosMo" +
            "vimientos", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerTodosMo" +
            "vimientosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.BackOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerTodosMo" +
            "vimientosProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Movimiento[] ObtenerTodosMovimientos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/AgregarMovimie" +
            "nto", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/AgregarMovimie" +
            "ntoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.BackOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/AgregarMovimie" +
            "ntoProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento AgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/BorrarMovimien" +
            "to", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/BorrarMovimien" +
            "toResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.BackOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/BorrarMovimien" +
            "toProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        void BorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ModificarMovim" +
            "iento", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ModificarMovim" +
            "ientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.BackOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ModificarMovim" +
            "ientoProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        void ModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntoXNombre", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntoXNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.BackOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntoXNombreProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento ObtenerMovimientoXNombre(string nombreMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntoXId", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntoXIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.BackOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntoXIdProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Movimiento ObtenerMovimientoXId(int idMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntosPaginando", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntosPaginandoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.BackOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IBackOfficeService/ObtenerMovimie" +
            "ntosPaginandoProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Movimiento[] ObtenerMovimientosPaginando(int pageNumber, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackOfficeServiceChannel : IndignadoFramework.UIProcess.BackOfficeService.IBackOfficeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackOfficeServiceClient : System.ServiceModel.ClientBase<IndignadoFramework.UIProcess.BackOfficeService.IBackOfficeService>, IndignadoFramework.UIProcess.BackOfficeService.IBackOfficeService {
        
        public BackOfficeServiceClient() {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackOfficeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IndignadoFramework.Entities.Movimiento[] ObtenerTodosMovimientos() {
            return base.Channel.ObtenerTodosMovimientos();
        }
        
        public IndignadoFramework.Entities.Movimiento AgregarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            return base.Channel.AgregarMovimiento(movimiento);
        }
        
        public void BorrarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            base.Channel.BorrarMovimiento(movimiento);
        }
        
        public void ModificarMovimiento(IndignadoFramework.Entities.Movimiento movimiento) {
            base.Channel.ModificarMovimiento(movimiento);
        }
        
        public IndignadoFramework.Entities.Movimiento ObtenerMovimientoXNombre(string nombreMovimiento) {
            return base.Channel.ObtenerMovimientoXNombre(nombreMovimiento);
        }
        
        public IndignadoFramework.Entities.Movimiento ObtenerMovimientoXId(int idMovimiento) {
            return base.Channel.ObtenerMovimientoXId(idMovimiento);
        }
        
        public IndignadoFramework.Entities.Movimiento[] ObtenerMovimientosPaginando(int pageNumber, int pageSize) {
            return base.Channel.ObtenerMovimientosPaginando(pageNumber, pageSize);
        }
    }
}
