//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignadoFramework.UIProcess.FrontOfficeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProcessExecutionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serena-yeoh//LayerSample/Expense/2007/08", ConfigurationName="FrontOfficeService.IFrontOfficeService")]
    public interface IFrontOfficeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ObtenerConvoc" +
            "atoriaXId", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ObtenerConvoc" +
            "atoriaXIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.FrontOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ObtenerConvoc" +
            "atoriaXIdProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.ConvocatoriaProjection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.CategoriaTematicaProjection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Convocatoria ObtenerConvocatoriaXId(int idConvocatoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/AgregarConvoc" +
            "atoria", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/AgregarConvoc" +
            "atoriaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.FrontOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/AgregarConvoc" +
            "atoriaProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.ConvocatoriaProjection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.CategoriaTematicaProjection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IndignadoFramework.Entities.MovimientoProjection))]
        IndignadoFramework.Entities.Convocatoria AgregarConvocatoria(IndignadoFramework.Entities.Convocatoria convocatoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/GetFeedsConvo" +
            "catoria", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/GetFeedsConvo" +
            "catoriaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.FrontOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/GetFeedsConvo" +
            "catoriaProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.WebFeed[] GetFeedsConvocatoria(int idConvocatoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ConfirmarAsis" +
            "tenciaConvocatoria", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ConfirmarAsis" +
            "tenciaConvocatoriaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.FrontOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ConfirmarAsis" +
            "tenciaConvocatoriaProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        void ConfirmarAsistenciaConvocatoria(int idConvocatoria, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ObtenerConvoc" +
            "atoriasMovimiento", ReplyAction="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ObtenerConvoc" +
            "atoriasMovimientoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoFramework.UIProcess.FrontOfficeService.ProcessExecutionFault), Action="http://serena-yeoh//LayerSample/Expense/2007/08/IFrontOfficeService/ObtenerConvoc" +
            "atoriasMovimientoProcessExecutionFaultFault", Name="ProcessExecutionFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoFramework.Services.Contracts")]
        IndignadoFramework.Entities.Convocatoria[] ObtenerConvocatoriasMovimiento(int idMovimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFrontOfficeServiceChannel : IndignadoFramework.UIProcess.FrontOfficeService.IFrontOfficeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FrontOfficeServiceClient : System.ServiceModel.ClientBase<IndignadoFramework.UIProcess.FrontOfficeService.IFrontOfficeService>, IndignadoFramework.UIProcess.FrontOfficeService.IFrontOfficeService {
        
        public FrontOfficeServiceClient() {
        }
        
        public FrontOfficeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FrontOfficeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrontOfficeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrontOfficeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IndignadoFramework.Entities.Convocatoria ObtenerConvocatoriaXId(int idConvocatoria) {
            return base.Channel.ObtenerConvocatoriaXId(idConvocatoria);
        }
        
        public IndignadoFramework.Entities.Convocatoria AgregarConvocatoria(IndignadoFramework.Entities.Convocatoria convocatoria) {
            return base.Channel.AgregarConvocatoria(convocatoria);
        }
        
        public IndignadoFramework.Entities.WebFeed[] GetFeedsConvocatoria(int idConvocatoria) {
            return base.Channel.GetFeedsConvocatoria(idConvocatoria);
        }
        
        public void ConfirmarAsistenciaConvocatoria(int idConvocatoria, int idUsuario) {
            base.Channel.ConfirmarAsistenciaConvocatoria(idConvocatoria, idUsuario);
        }
        
        public IndignadoFramework.Entities.Convocatoria[] ObtenerConvocatoriasMovimiento(int idMovimiento) {
            return base.Channel.ObtenerConvocatoriasMovimiento(idMovimiento);
        }
    }
}
